// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Profanity.Data;

namespace Profanity.Data.Migrations
{
    [DbContext(typeof(ProfanityServiceDbContext))]
    [Migration("20210515213312_change data format")]
    partial class changedataformat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Profanity.Data.Entities.ProfanityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProfanityWord")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("ProfanityEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
